apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amandeeprana/inventoryproject_backend:latest  # Use 'latest' for CI/CD updates
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: DATABASE_HOST
            value: mysql-service
          - name: DATABASE_USER
            value: root
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-credentials
                key: mysql-root-password
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-root-credentials
                key: mysql-database
          - name: FLASK_APP
            value: app.py
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          - name: FLASK_RUN_PORT
            value: "4000"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002

