apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: LoadBalancer 
  ports:
  - port: 3001
    targetPort: 80
    nodePort: 30412
    protocol: TCP
  selector:
    app: frontend
