apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ppvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Request 5 Gigabytes of storage
      storage: 5Gi
