
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-credentials
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: QXByYW5hQDEyMzQ1IQ==
  mysql-database: bXlfcHl0aG9uX2FwcF9kYg==
